/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\Models\Table.gltf 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useConfigurator } from "../Context/configurator";
import * as Three from "three";
import { useFrame, useThree } from "@react-three/fiber";

const ANIM_SPEED = 12;

export function Table(props) {
  const { nodes, materials } = useGLTF("./Models/Table.gltf");
  const { legs, legsColor, tableWidth, tableHeight, tableLength } =
    useConfigurator();
    const {scene}  = useThree()
  const plate = useRef();
  const leftLegs = useRef();
  const rightLegs = useRef();

  useEffect(() => {
    materials.Metal.color = new Three.Color(legsColor);
  }, [legsColor]);

  useFrame((state, delta) => {

    const tableWidthScale = tableWidth / 100;
    const tableLengthScale = tableLength / 100;
    // const tableHeightScale = tableHeight / 100;


    //plate width
    const targetScale = new Three.Vector3(tableWidthScale, 1, tableLengthScale);
    plate.current.scale.lerp(targetScale, delta * ANIM_SPEED);
    // plate.current.position.y = tableHeightScale;
    // Left legs
    const targetLeftPosition = new Three.Vector3(-1.5 * tableWidthScale, 0, 0);
    // width
    leftLegs.current.position.lerp(targetLeftPosition, delta * ANIM_SPEED);
    // Length
    leftLegs.current.scale.lerp(targetScale, delta * ANIM_SPEED);
    // leftLegs.current.scale.y =1+ -tableHeightScale;
    // Right legs
    const targetRightPosition = new Three.Vector3(1.5 * tableWidthScale, 0, 0);
    // width
    rightLegs.current.position.lerp(targetRightPosition, delta * ANIM_SPEED);
    // Length
    rightLegs.current.scale.lerp(targetScale, delta * ANIM_SPEED);
    // rightLegs.current.scale.y =1+ -tableHeightScale;
});
console.log(materials.Plate);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plate.geometry}
        material={materials.Plate}
        castShadow
        // position={[0,tableHeight,0]}
        // scale={[tableWidthScale, 1, tableLengthScale]}
        ref={plate}
      />

      {legs === 0 && (
        <>
          <mesh
            geometry={nodes.Legs01Left.geometry}
            material={materials.Metal}
            position={[-1.5, 0, 0]}
            castShadow
            ref={leftLegs}
            // scale={[1, tableHeight, tableLengthScale]}
          />
          <mesh
            geometry={nodes.Legs01Right.geometry}
            material={materials.Metal}
            position={[1.5, 0, 0]}
            // scale={[1, tableHeight,tableLengthScale]}
            ref={rightLegs}
          />
        </>
      )}
      {legs === 1 && (
        <>
          <mesh
            geometry={nodes.Legs02Left.geometry}
            material={materials.Metal}
            position={[-1.5, 0, 0]}
            castShadow
            // scale={[1, tableHeight, tableLengthScale]}
            ref={leftLegs}
          />
          <mesh
            geometry={nodes.Legs02Right.geometry}
            material={materials.Metal}
            position={[1.5, 0, 0]}
            // scale={[1, tableHeight, tableLengthScale]}
            ref={rightLegs}
          />
        </>
      )}
      {legs === 2 && (
        <>
          <mesh
            geometry={nodes.Legs03Left.geometry}
            material={materials.Metal}
            position={[-1.5, 0, 0]}
            castShadow
            // scale={[1, tableHeight, tableLengthScale]}
            ref={leftLegs}
          />
          <mesh
            geometry={nodes.Legs03Right.geometry}
            material={materials.Metal}
            position={[1.5, 0, 0]}
            castShadow
            // scale={[1, tableHeight, tableLengthScale]}
            ref={rightLegs}
          />
        </>
      )}
    </group>
  );
}

useGLTF.preload("./Models/Table.gltf");
